{{- $values := index .Values "virtualhost" -}}
{{- if $values }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include "default.fullname" . }}-http-proxy
  labels:
    {{- include "default.labels" . | nindent 4 }}
  {{- with .Values.httpproxyAnnotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: {{ $values.host }}
    tls:
      secretName: wildcard-{{ trimAll "*." $values.certhost }}
  routes:
    - conditions:
        - prefix: /
      services:
        - name: {{ include "default.fullname" . }}
          port: {{ .Values.service.port | int }}
{{- if hasKey $values "protocol" }}
          protocol: {{ $values.protocol }}
      timeoutPolicy:
        response: infinity
        idle: infinity
{{- end }}
{{- end }}
