apiVersion: v1
kind: Service
metadata:
  name: {{ include "default.fullname" . }}
  labels:
    {{- include "default.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | int }}
      targetPort: {{ .Values.service.name }}
      protocol: TCP
      name: {{ .Values.service.name }}
    - port: {{ .Values.service.metrics.port | int }}
      protocol: TCP
      targetPort: {{ .Values.service.metrics.name }}
      name: {{ .Values.service.metrics.name }}
  selector:
    {{- include "default.selectorLabels" . | nindent 4 }}
