version: '3.8'
services:
  db:
    env_file:
     - ./.env
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    image: postgres:14.1-alpine
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
    container_name: postgres-14.1-alpine-testtask
    restart: always
