apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-arm-tests.deeplay.io-cert
  namespace: arm-tests
spec:
  commonName: '*.arm-tests.deeplay.io'
  dnsNames:
    - '*.arm-tests.deeplay.io'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: wildcard-arm-tests.deeplay.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildcard-arm-tests.deeplay.io-ingress
  namespace: arm-tests
spec:
  ingressClassName: contour
  rules:
    - host: '*.arm-tests.deeplay.io'