apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-deployer
  namespace: arm-tests
---
apiVersion: v1
kind: Secret
metadata:
  name: github-deployer-secret
  namespace: arm-tests
  annotations:
    kubernetes.io/service-account.name: github-deployer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions
  namespace: arm-tests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: github-deployer