{{- if hasKey .Values "vpa" }}
{{- $values := index .Values "vpa" -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "default.fullname" . }}-vpa
  labels:
    {{- include "default.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ include "default.fullname" . }}
  updatePolicy:
    updateMode: "Off"
  {{- if hasKey $values "resourcePolicy" }}
  resourcePolicy:
    {{- toYaml $values.resourcePolicy | nindent 4 }}
  {{- end }}
{{- end}}
