name: common helm chart deploy
on:
  workflow_dispatch:


defaults:
  run:
    working-directory: ./

jobs:
  prepare_helm:
    runs-on:
      - self-hosted
      - Linux
      - kube-common
    container:
      image: quay.io/roboll/helmfile:v0.142.0
    env:
      HELM_EXPERIMENTAL_OCI: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Bump version and push tag
      id: new-tag
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ""
        append_to_pre_release_tag: ''

    - name: Lint helm chart
      run: |
        sed -i "s/version\:.*/version\: ${{ steps.new-tag.outputs.new_tag }}/" ./app/Chart.yaml
        helm lint ./app

    - name: Push helm chart
      run: |
        helm registry login https://registry.deeplay.io/ --username '${{ secrets.DOCKER_USERNAME_DEEPLAY }}' --password '${{ secrets.DOCKER_PASSWORD_DEEPLAY }}'
        helm package ./app
        helm push common-helm-chart-${{ steps.new-tag.outputs.new_tag }}.tgz oci://registry.deeplay.io/arm/common-helm-chart
        rm common-helm-chart-${{ steps.new-tag.outputs.new_tag }}.tgz
